name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    steps:
     - name: my first app
       env: 
         MY_VAR: Hi there! my names is
         FIRST_NAME: Quetzalcoatl
         MIDDLE_NAME: Garcia
         LAST_NAME: Lagunas
       run: echo $MY_VAR $FIRTS_NAME $MIDDLE_NAME $LAST_NAME
